// Phase 1.2 — ember theme: values identical to the current singleton.
// Ember brand deltas (§2) land in Phase 5, never here.
import type { Theme } from "../theme.js";

export const emberTheme: Theme = {
  color: {
    background: undefined as string | undefined,
    foreground: undefined as string | undefined,
    primary: undefined as string | undefined,
    mutedPaint: "gray",
    selection: "green",
    menuSelection: "green",
    questionSelection: "green",
    user: "#6EA8FF",
    assistant: "magenta",
    inputPrompt: "cyan",
    activity: "yellow",
    tool: undefined as string | undefined,
    toolError: "red",
    success: "green",
    warning: "yellow",
    error: "red",
    permission: "yellow",
    code: "green",
    link: "cyan",
    heading: undefined as string | undefined,
    synKeyword: "magenta",
    synString: "yellow",
    synNumber: "cyan",
    diffAddBg: "green",
    diffDelBg: "red",
    diffChangedFg: "black",
    bannerA: "#6EA8FF",
    bannerB: "magenta",
    headerBranch: "green",
    composerFocus: "cyan",
    composerBusy: "yellow",
    badgeUser: "#6EA8FF",
    badgeAssistant: "magenta",
    quoteAccent: "cyan",
    ruleDim: true as boolean,
    question: "magenta",
  },
  border: {
    style: "round" as const,
    input: "gray",
    picker: "green",
    menu: "cyan",
    panel: "cyan",
    approval: "yellow",
    question: "magenta",
    tool: {
      ok: "green",
      fail: "red",
      denied: "yellow",
      running: "yellow",
      queued: "gray",
    },
  },
  spacing: {
    rowIndent: "  ",
    codeIndent: "  ",
    pickerPadX: 1,
    widgetPadX: 1,
    turnGap: 1,
    liveTailMarginY: 1,
    statusMarginTop: 1,
    inputInset: 6,
    statusDefaultColumns: 100,
    statusXsColumns: 50,
    statusGoalObjectiveChars: 32,
    statusBusyGoalChars: 48,
  },
  symbol: {
    select: "❯",
    bullet: "•",
    quoteBar: "│",
    moreAbove: "↑",
    moreBelow: "↓",
    separator: "·",
    descSeparator: "—",
    bar: "│",
    rule: "─",
    ellipsis: "…",
    running: "◌",
    thinking: "💭",
    workThinking: "◐",
    workTool: "◉",
    retryMark: "↻",
    detailMark: "↳",
    warningMark: "⚠",
    toolMark: "⚙",
    cursorBar: "▍",
    cursorBlock: "█",
    inputPrompt: "›",
    keyMask: "•",
    keyPresent: "✓",
    toolOk: "✓",
    toolFail: "✕",
    toolDenied: "⊘",
    toolQueued: "○",
    toolRunning: "◉",
    toolSuccess: "✓",
    toolFailed: "✕",
    toolCancelled: "◌",
    kindTerminal: "terminal",
    kindFile: "file",
    kindSearch: "search",
    kindWeb: "web",
    kindTodo: "todo",
    kindVision: "vision",
    kindGeneric: "tool",
    taskDone: "✅",
    taskActive: "🔧",
    taskPending: "○",
    taskDoneBox: "☑",
    taskDoneEmpty: "☐",
    speakerUser: "you>",
    speakerAssistant: "ATOM>",
    questionStep: "Q",
  },
} as const;
