// Phase 5.1 — ember theme: Ember brand deltas (plan §2) applied.
// Classic file stays verbatim; legacy singleton untouched.
import type { Theme } from "../theme.js";

export const emberTheme: Theme = {
  color: {
    background: undefined as string | undefined,
    foreground: undefined as string | undefined,
    primary: undefined as string | undefined,
    mutedPaint: "gray",
    selection: "green",
    menuSelection: "green",
    questionSelection: "green",
    user: "#6EA8FF",
    assistant: "magenta",
    inputPrompt: "cyan",
    activity: "yellow",
    tool: undefined as string | undefined,
    toolError: "red",
    success: "green",
    warning: "yellow",
    error: "red",
    permission: "yellow",
    code: "green",
    link: "cyan",
    heading: undefined as string | undefined,
    synKeyword: "magenta",
    synString: "yellow",
    synNumber: "cyan",
    diffAddBg: "green",
    diffDelBg: "red",
    diffChangedFg: "black",
    bannerA: "#F5A524",
    bannerB: "magenta",
    headerBranch: "green",
    composerFocus: "#F5A524",
    composerBusy: "yellow",
    badgeUser: "#6EA8FF",
    badgeAssistant: "magenta",
    quoteAccent: "cyan",
    ruleDim: true as boolean,
    question: "magenta",
  },
  border: {
    style: "round" as const,
    input: "gray",
    picker: "green",
    menu: "cyan",
    panel: "cyan",
    approval: "yellow",
    question: "magenta",
    tool: {
      ok: "green",
      fail: "red",
      denied: "yellow",
      running: "yellow",
      queued: "gray",
    },
  },
  dock: {
    border: "gray",
    borderStyle: "single" as const,
    padX: 1,
    divider: "─",
  },
  // Phase 5.1 — pill tokens (plan §2.2, new namespace). Labels always dim;
  // values carry meaning. `stalled` shares the error row (red/yellow).
  pill: {
    label: "dim",
    model: "#F5A524",
    token: "cyan",
    goalActive: "magenta",
    goalPaused: "gray",
    branch: "green",
    modeNormal: "green",
    modeYolo: "yellow",
    modePlan: "yellow",
    approval: "yellow",
    error: "red",
    stalled: "yellow",
  },
  spacing: {
    rowIndent: "  ",
    codeIndent: "  ",
    pickerPadX: 1,
    widgetPadX: 1,
    turnGap: 1,
    liveTailMarginY: 1,
    statusMarginTop: 1,
    inputInset: 6,
    statusDefaultColumns: 100,
    statusXsColumns: 50,
    statusGoalObjectiveChars: 32,
    statusBusyGoalChars: 48,
  },
  symbol: {
    select: "❯",
    bullet: "•",
    quoteBar: "│",
    moreAbove: "↑",
    moreBelow: "↓",
    separator: "·",
    descSeparator: "—",
    bar: "│",
    rule: "─",
    ellipsis: "…",
    running: "◌",
    thinking: "◐",
    workThinking: "◐",
    workTool: "◉",
    retryMark: "↻",
    detailMark: "↳",
    warningMark: "⚠",
    toolMark: "⚙",
    cursorBar: "▍",
    cursorBlock: "█",
    inputPrompt: "›",
    keyMask: "•",
    keyPresent: "✓",
    toolOk: "✓",
    toolFail: "✕",
    toolDenied: "⊘",
    toolQueued: "○",
    toolRunning: "◉",
    toolSuccess: "✓",
    toolFailed: "✕",
    toolCancelled: "◌",
    kindTerminal: "terminal",
    kindFile: "file",
    kindSearch: "search",
    kindWeb: "web",
    kindTodo: "todo",
    kindVision: "vision",
    kindGeneric: "tool",
    taskDone: "✓",
    taskActive: "◉",
    taskPending: "○",
    taskDoneBox: "☑",
    taskDoneEmpty: "☐",
    speakerUser: "you>",
    speakerAssistant: "ATOM›",
    questionStep: "Q",
  },
  // Widening cast (ember-only): Phase 5 deltas intentionally diverge from
  // the legacy literal types, and `pill` is a new namespace the base
  // `Theme` type reserves as never-valued. Runtime carries full values;
  // `Theme` stays the consumer type so the registry is untouched.
} as unknown as Theme;
